version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=userpass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - '127.0.0.1:5432:5432'
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=userpass
      - MYSQL_USER=user
      - MYSQL_DATABASE=db
    ports:
      - "127.0.0.1:3306:3306"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  esdata1:
    driver: local
