version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: 1

      - image: mongo

    steps:
      - checkout

      - run: 
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      
      - restore_cache:
          key: deps-{{ checksum "Pipfile.lock" }}
      
      - run:
          name: Install all dependencies to start testing
          command: |
            pipenv install --dev

      - save_cache:
          key: deps-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      
      - run: 
          name: Start tests
          command: |
            pipenv run pytest --junitxml=test-reports/pytest/junit.xml --ignore=tests/integrations/test_mysql_integration.py --ignore=tests/integrations/test_postgre_integration.py  tests

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports